name: Deploy Backend

on:
  workflow_dispatch: # <--- ADDS THE MANUAL BUTTON
  push:
    branches: [ "main" ]
    # paths:       <--- DELETE THESE 2 LINES TEMPORARILY
    #  - 'backend/**'

jobs:
  # JOB 1: BUILD (Runs on GitHub's computers)
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Backend Image
        run: |
          docker build -t qaiem/fyp-server:latest ./backend
          docker push qaiem/fyp-server:latest

  # JOB 2: DEPLOY (Runs on your AWS EC2)
  deploy:
    needs: build  # This waits for the 'build' job to finish
    runs-on: self-hosted
    steps:
      - name: Pull Docker Image
        run: |
          docker pull qaiem/fyp-server:latest
          
      - name: Run Backend Container
        run: |
          docker stop backend-container || true
          docker rm backend-container || true
          # We pass the secret here because this runs on your server
          docker run -d -p 4000:4000 -e MONGO_URI='${{ secrets.MONGO_URI }}' --name backend-container qaiem/fyp-server:latest