name: Deploy Frontend
on:
  push:
    branches: [ "main" ]
    paths:
      - 'frontend/**'  # Only runs when frontend folder changes

jobs:
  # JOB 1: BUILD (Runs on GitHub's computers)
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Frontend Image
        run: |
          # ⚠️ REPLACE 'qaiem/fyp-client' with your actual Frontend Repo Name from Docker Hub
          docker build -t qaiem/fyp-client:latest ./frontend
          docker push qaiem/fyp-client:latest

  # JOB 2: DEPLOY (Runs on your AWS EC2)
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Docker Image
        run: |
          # ⚠️ REPLACE 'qaiem/fyp-client' here too
          docker pull qaiem/fyp-client:latest
          
      - name: Run Frontend Container
        run: |
          docker stop frontend-container || true
          docker rm frontend-container || true
          
          # Mapping Port 3000 (EC2) -> Port 80 (Container/Nginx)
          docker run -d -p 3000:80 --name frontend-container qaiem/fyp-client:latest